### ISSUE TITLE
How to set up grpc in Mumur.ini file?

### ISSUE THREAD

**Issue by SonPham1602** [theAkito/docker-murmur#1]
Hi @theAkito. First of all. Thank for you project. I have a question that I want to use murmur-cli to using murmur api with grpc. But I saw that line.  But when I using command line "murmur-cli --address="127.0.0.50051  --insecure=false   meta events " . It's not run. How to solve this problem?  Should I add cert and key.
![image](https://user-images.githubusercontent.com/43876888/121798535-2def3200-cc51-11eb-9c1c-fa6c86d68e2c.png)

Murmur cli : https://github.com/layeh/murmur-cli

**Comment by theAkito** [comment]
See https://github.com/layeh/murmur-cli/issues/4#issuecomment-860278613
