### ISSUE TITLE
Building with current master branch

### ISSUE THREAD

**Issue by ghost** [theAkito/docker-murmur#2]
Hi,

I'm fixing the Dockerfile to work with bullseye-slim and the latest git master tree. They moved on to cmake, and Bullseye is needed to have cmake >3.15.

Beyond that, the qt packages have been renamed and there are some issues with the Python interpreter detection I'm working on.

**Comment by theAkito** [comment]
Greetings! 👋🏻 

Thanks for letting me know! If you are implying, I should improve my image accordingly, would you show me the repository where you are working on it? I did not find any which has "mumble" or "murmur" in its name, which you are working on.

I would also take a look and perhaps try to fix something, if it does not work.

**Comment by ghost** [comment]
I can provide you the edited Dockerfile, it's working :-)

I will see if I can setup a fork here and push the changes, and send a PR your way.

**Comment by theAkito** [comment]
Obsolete.
